server:
  port: 8888

spring:
  profiles:
    active: dev
    
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-brlk9.pub-cdb.ntruss.com/kalo_test?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: user
    password: user1234U
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database:  mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        default-page-size: 10
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-brlk9.pub-cdb.ntruss.com/kalo_main?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: user
    password: user1234U
  jpa:
    hibernate:
      ddl-auto: none
    database:  mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        default-page-size: 10
springdoc:
  api-docs: 
    enabled: false
  swagger-ui:
    enabled: false


logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework.web.servlet.DispatcherServlet: DEBUG