server:
  port: 8888

spring:
  profiles:
    active: main
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-brlk9.pub-cdb.ntruss.com/kalo_test
    username: user
    password: user1234U
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database:  mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        default-page-size: 5
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE